version: 2

sources:
  - name: raw        
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Raw sales data

      - name: product
        identifier: raw_gz_product
        description: Raw product data

      - name: ship
        identifier: raw_gz_ship
        description: Raw shipping data